# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Win32API-File-Time
version:      0.005
version_from: Time.pm
installdirs:  site
requires:
    Win32::API:                    0.01
    Win32API::File:                0.08

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
